### ISSUE TITLE
Can't install plinkio on RHEL

### ISSUE THREAD

**Issue by labuve** [mfranberg/libplinkio#15]
Hello!

I've been trying to install plinkio and used the command `pip install plinkio`. But it throws an error message "command 'gcc' failed with exit status 1". I made sure gcc is installed and upgraded both pip and setuptools. The current version of installed pip is 10.0.1. I have python 2.7.

I would appreciate any help!

Thank you!

**Comment by mfranberg** [comment]
Hi! Sorry for my slow reply.

Could you check if you have python-dev installed as well? To be able to compile plinkio gcc needs access to some definitions that are available through the header Python.h. You can install it by:

```sudo apt-get install python-dev```

**Comment by labuve** [comment]
There is no command apt-get installed. I tried `sudo yum install python-dev`, but it cannot find the package. The same thing happens with `python-devel` package, since some threads also suggested installing that package.

**Comment by labuve** [comment]
I am sorry, somehow the issue magically resolved itself and I have been able to install both python-devel and plinkio. Anyway, thanks for all the support! :)

**Comment by mfranberg** [comment]
I'm glad to hear, sorry for the slow support :-)
