### ISSUE TITLE
Fam file containing character phenotypes

### ISSUE THREAD

**Issue by choishingwan** [mfranberg/libplinkio#16]
If the fam file contain character phenotypes or contains solely of NA, libplinkio will return the following error message:

`IOError: Error while trying to open the FAM plink file.`

Will it be possible for one to read in this kind of FAM file? Providing that the users are also submitting a phenotype file.

**Comment by mfranberg** [comment]
Character phenotypes is not supported at the moment. I guess one way to not crash would be to add an option to treat them as NA for the time being, would that work for you?

However, if it solely contains NA then it should work. I'll take a look at it, thank you for reporting.

**Comment by choishingwan** [comment]
Yes, that’d work fine. I tried to use NA as phenotypes as that didn’t work
either, maybe I didn’t used it correctly?

**Comment by mfranberg** [comment]
I apologize for an extremely slow reply. I have added support NA as of 51889398ed59502ba3cd8c474e80ee01d7a7ffd4.
