### ISSUE TITLE
Error in importing plinkfile

### ISSUE THREAD

**Issue by aritra90** [mfranberg/libplinkio#17]
Hi I was trying to work with this in Python. 
I installed it using pip (as instructed in the Readme) and then tried to run the sample python code provided. However when I try to import plinkfile it is giving me this following error: 
ImportError: /home/bose6/.local/lib/python2.7/site-packages/plinkio/cplinkio.so: undefined symbol: _intel_fast_memcpy

Do I have to configure anything else? Any help is appreciated.

**Comment by labuve** [comment]
Hi! I am encountering a similar problem. I have installed an earlier version of plinkio (0.9.5), which I believe I have been using before successfully. But now when I try to run `from plinkio import plinkfile` it spits out a similar message:
_ImportError: /home/rustich0/njandaro/.local/lib/python3.6/site-packages/plinkio/cplinkio.cpython-36m-x86_64-linux-gnu.so: undefined symbol: PyInt_AsLong_
I was wondering, if you found solution for your issue?
Thank you!
