### ISSUE TITLE
FAM file parsing: Relation between phenotype and affection

### ISSUE THREAD

**Issue by yakkoroma** [mfranberg/libplinkio#18]
We used as input a FAM file with 6 columns that are the following:
IID, FID, Mother ID, FatherID, Sex, Phenotype.
The latter, phenotype, is represented by 1 (controls), 2(cases), and -9 (missing) in according to PLINK documentation.

Once processed by plinkf.get_samples(), the output file we got has two properties that are:
Phenotype and affection. 
Affection represents the original phenotype column of the FAM input file (with case =1, control = 0, missing = -9)
The phenotype property has values 0 and 1.  How does phenotype property correlate with Affection? and How is phenotype property generated?

Thank you in advance for your reply

**Comment by mfranberg** [comment]
Hi @yakkoroma!

This seems to be a bug, when the phenotype is -9 only affection is set properly to missing, phenotype can be any value. I'll make a fix for it.

**Comment by mfranberg** [comment]
Sorry for very slow response time, it should be fixed in 42c6aa26580b28790db0951b99ee5b29f0e92302. I'll release a new version in short once I have dealt with the other issues.
