### ISSUE TITLE
Error in opening bim file

### ISSUE THREAD

**Issue by nurfatimaj** [mfranberg/libplinkio#19]
Hi!

The description of the problem is rather long and it just shows that I don't even know where is the error. In short, I am trying to run LDpred program that relies on plinkio to open .bed and .bim files. But I keep getting the following message, which I managed to trace to plinkio package.

> OSError: Error while trying to open the BIM plink file

I have plinkio version 0.9.7 installed and I ran only these two codes: `from plinkio import plinkfile` and `plinkfile.open("input_genetic_file")`. I specify input_genetic_file without extensions. If I provide an extension (either .bim, .fam or .bed), the error message changes from "BIM" to "BED" plink file. The genetic files are valid as I am able to work with them using the command line PLINK.

I have been working with LDpred back in April and I did not have any of these problems back then. So, one thing I tried to do was to install a version of plinkio from Jan 22, 2019 (0.9.5 or 0.9.4). I failed to install version 0.9.4 due to some error with gcc. With 0.9.5 version, I cannot import the package in python as the following error is displayed:
> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rustich0/njandaro/.local/lib/python3.6/site-packages/plinkio/plinkfile.py", line 1, in <module>
    from . import cplinkio
ImportError: /home/rustich0/njandaro/.local/lib/python3.6/site-packages/plinkio/cplinkio.cpython-36m-x86_64-linux-gnu.so: undefined symbol: PyInt_AsLong

Any comment on the issue would be appreciated since I couldn't find much googling.

Thank you!

**Comment by pgormley** [comment]
Same issue here! Any fix yet?

**Comment by brianzhang01** [comment]
PyInt_AsLong does not exist in Python 3, it should be replaced with PyLong_AsLong. Maybe try downloading a previous version and manually adding in the redefines here.

https://github.com/mfranberg/libplinkio/blob/master/py-plinkio/cplinkio.c#L78

**Comment by mfranberg** [comment]
Hi sorry for the embarrassingly slow reaction time on this, it should be resolved in the latest release 0.9.8. If you still see an issue please reach out.

**Comment by adamklie** [comment]
I have run into the exact same issue even with `plinkio` v0.9.8.

**Comment by akhilpampana** [comment]
Hello, I am trying "LDpred" recently and it is installed "plinkio" which is the latest "0.9.8" but still getting the above error. Please do let me know if it can be fixable. I am using Python 3.7 for the tool.

**Comment by riasc** [comment]
Same here. Getting this error on 0.9.8. Is there any update on this?
