### ISSUE TITLE
python wrapper function read_bedbimfam

### ISSUE THREAD

**Issue by shadiakiki1986** [mfranberg/libplinkio#24]
I created a wrapper function to simplify reading plink files in python using libplinkio. It is defined and illustrated in this jupyter notebook https://gist.github.com/shadiakiki1986/336606ab067052203607309a3ee2d7a4

Would this be suitable for a PR?

**Comment by mfranberg** [comment]
Hi @shadiakiki1986 sorry for the slow response and thank you for the contribution. I try to keep this library to have as few dependencies as possible, so pandas and numpy would be too much. But feel free to make a library wrapping this one, I for one, think it is very useful to get out a dataframe.

**Comment by mfranberg** [comment]
I will close this issue.
