### ISSUE TITLE
WritablePlinkFile segfaults when Samples have ints instead of strings

### ISSUE THREAD

**Issue by Wainberg** [mfranberg/libplinkio#4]
This segfaults:

    from plinkio.plinkfile import WritablePlinkFile, Sample; WritablePlinkFile('foo', [Sample(0, 0, 0, 0, 0, 0)])

**Comment by mfranberg** [comment]
I agree, will take a look at it tomorrow. Thanks for noticing it!

**Comment by Wainberg** [comment]
Thanks for the quick response!  Love your library.

**Comment by mfranberg** [comment]
I committed a fix to this now. Now it will try to convert to the appropriate type, and if not possible a TypeError is raised. Thanks for finding a simple example to test on, I can imagine that it caused quite a headache.

I will submit this to pip at the end of the week, so if you want to try the changes you need to use the github source.
