### ISSUE TITLE
undefined symbol: PyInt_AsLong

### ISSUE THREAD

**Issue by freeseek** [mfranberg/libplinkio#5]
I compiled and installed with the "pip3 --install --user plinkio" command. However, when I try the command "from plinkio import plinkfile" I receive the error "/home/########/.local/lib/python3.4/site-packages/plinkio/cplinkio.cpython-34m.so: undefined symbol: PyInt_AsLong". The problem does not exist using python 2.7.9.

**Comment by mfranberg** [comment]
Thank you freeseek, I will fix the Python 3 issues tomorrow. I have kind of neglected python 3 support for a while, sorry!

**Comment by mfranberg** [comment]
Ok, so the Python3 issues should be fixed in commit 58da1206a4bc7491c2a894a632b411762ae83407. At least it installs correctly on Linux and Mac for me through pip. Thanks for brining it to my attention, I'll be happy to reopen this issue if you find any further issues.
