### ISSUE TITLE
Installing plinkio on Windows machine

### ISSUE THREAD

**Issue by cullenaroberts** [mfranberg/libplinkio#9]
Pip does not install plinkio on Windows machine, apparently because C dependencies ("strings.h", "unistd.h","ansi.h") are not satisfied.  

What needs to be done so that plinkio can be installed on a windows machine?

**Comment by mfranberg** [comment]
I apologize for a slow response, been a busy week. Currently this library is not supported on Windows and I have no plan for porting it to Windows. I'm not sure exactly what needs to be done to port this library to Windows, but feel free to dig into it and set-up a pull request.

Two alternatives might be to: 1) Build it using Cygwin or 2) set-up a docker image that includes this library.

**Comment by cullenaroberts** [comment]
1) I tried building it with cygwin and had a lot of issues.  I'm not a unix
expert, but I talked to one (he helps run my university's servers), and he
doesn't think it's possible for cygwin to fix the underlying problems.

1*) So I am trying a virtual machine on my windows machine.   I can't
install linux on my university's secure computers (data use contracts
specify operating system, it can take months to alter those contracts.  It
once took me over a year to get a contract changed).  Hopefully a virtual
machine on a thumbdrive will get around that problem.

2) I'm unfamiliar with docker images.  I'll look that up.

Thanks for replying to me.

**Comment by ofrei** [comment]
I've used libplinkio on Windows 10 from WSL (ubuntu subsystem), and it worked very nicely. But it would be tricky to make libplinkio into a real windows executable and complie it with, for example, Visual Studio compiler. One reason is that libplinkio uses ``mmap`` function from ``<sys/mman.h>`` to work with memory-mapped files -- I'm not aware of any easy way of making this work on Windows (unless via ``mapped_file`` from boost libraries, but such dependency would be too heavy for libplinkio.

**Comment by mfranberg** [comment]
In this case mmap is only used for the transpose functionality, so an alternative would be not to support that on windows (or write an alternative implementation).

**Comment by mfranberg** [comment]
With #26, you can now compile libplinkio using the mingw compiler (GCC for windows).
